// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cfe6d848-1357-49ea-92c4-2ef46a846719",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_AWHIn3lP3",
    "aws_user_pools_web_client_id": "5pcct8i9a8r3gqitoq8hpo5lk"
};


export default awsmobile;
